frr defaults traditional
hostname deb-1
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.1/32
!
interface eth1
 ip address 10.255.0.0/31
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth2
 ip address 10.255.0.2/31
 ip ospf area 0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.0.0.1
 network 10.0.0.1/32 area 0
 network 10.255.0.0/31 area 0
 network 10.255.0.2/31 area 0
 passive-interface lo
!
router bgp 65001
 bgp router-id 10.0.0.1
 no bgp ebgp-requires-policy
 neighbor 10.255.0.1 remote-as 65002
 neighbor 10.255.0.3 remote-as 65002
 !
 address-family ipv4 unicast
  network 10.0.0.1/32
  neighbor 10.255.0.1 activate
  neighbor 10.255.0.3 activate
 exit-address-family
!
line vty
!
