[tox]
envlist =
;    py37
;    py38
;    py39
;    py310
    py311
    py312
    py313
;    pypy39
    pypy310
    mypy
    lint

[testenv]
passenv = *
deps =
    pytest
    pytest-asyncio
;changedir = ./tests
commands =
    pytest -rP tests

[testenv:mypy]
deps = mypy
commands =
    - mypy --strict src

[testenv:lint]
deps =
    black
    isort[colors]
    flake8
commands =
    - black --check --diff --color src
    - isort --check --diff --color src
    - flake8 src

[flake8]
max-line-length = 120
