Host p?? r?? h?? 192.168.0.*
    ProxyJump omega
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    ServerAliveInterval 20
    ServerAliveCountMax 3

Host p11
    HostName 192.168.0.1

Host p12
    HostName 192.168.0.2

Host p21
    HostName 192.168.0.3

Host p22
    HostName 192.168.0.4

Host r11
    HostName 192.168.0.5

Host r12
    HostName 192.168.0.6

Host r21
    HostName 192.168.0.7

Host r22
    HostName 192.168.0.8

Host h11
    HostName 192.168.0.11

Host h12
    HostName 192.168.0.12

Host h21
    HostName 192.168.0.21

Host h22
    HostName 192.168.0.22
