frr defaults traditional
hostname deb-1
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.2/32
!
interface eth1
 ip address 10.255.0.1/31
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth2
 ip address 10.255.0.3/31
 ip ospf area 0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.0.0.2
 network 10.0.0.2/32 area 0
 network 10.255.0.1/31 area 0
 network 10.255.0.3/31 area 0
 passive-interface lo
!
router bgp 65002
 bgp router-id 10.0.0.2
 no bgp ebgp-requires-policy
 neighbor 10.255.0.0 remote-as 65001
 neighbor 10.255.0.2 remote-as 65001
 !
 address-family ipv4 unicast
  network 10.0.0.2/32
  neighbor 10.255.0.0 activate
  neighbor 10.255.0.2 activate
 exit-address-family
!
line vty
!
